apiVersion: v1
kind: Service
metadata:
  name: boardgame-svc
  namespace: board-games
spec:
  type: ClusterIP
  selector:
    app: boardgame
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
